# Generated by Django 4.0.4 on 2022-04-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeDownloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
