# Generated by Django 4.0.4 on 2022-04-15 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('YoutubeDownloader', '0004_alter_task_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_added',
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=50),
        ),
    ]
