# Generated by Django 4.0.4 on 2022-04-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeDownloader', '0005_remove_task_date_added_task_owner_alter_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(),
        ),
    ]
