# Generated by Django 4.0.4 on 2022-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeDownloader', '0006_alter_task_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.TextField(default='teddy171@qq.com'),
            preserve_default=False,
        ),
    ]
